<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BatterySeeder extends Seeder
{
    public function run(): void
    {
        DB::table('batteries')->insert([
            [
                'name' => 'EcoCharge HomeVault 10',
                'manufacturer_id' => 5,
                'price' => 1499.0,
                'capacity' => 10.0,
                'description' => 'The HomeVault 10 is a 10kWh LiFePO4 battery designed for whole-home backup. It features an advanced Battery Management System (BMS) for optimal safety and a 6,000 cycle life.',
            ],
            [
                'name' => 'Quantum EnergyBank 5',
                'manufacturer_id' => 15,
                'price' => 750.0,
                'capacity' => 5.0,
                'description' => 'Store your solar energy with the Quantum EnergyBank 5. This 5kWh unit uses safe LiFePO4 technology for reliable, long-lasting performance. Perfect for self-consumption and peak shaving.',
            ],
            [
                'name' => 'AuraPower Reserve 15',
                'manufacturer_id' => 4,
                'price' => 1999.0,
                'capacity' => 15.0,
                'description' => 'Achieve energy independence with the AuraPower Reserve 15, a scalable 15kWh storage solution. Its modular, stackable design allows for easy installation and future expansion.',
            ],
            [
                'name' => 'VoltStorage Core 2.5',
                'manufacturer_id' => 25,
                'price' => 299.99,
                'capacity' => 2.5,
                'description' => 'The VoltStorage Core 2.5 is a compact 2.5kWh LFP battery. It\'s an ideal entry-point for solar storage, helping you optimize self-consumption and reduce your electricity bills.',
            ],
            [
                'name' => 'AmpereDrive Titan 12',
                'manufacturer_id' => 2,
                'price' => 1750.0,
                'capacity' => 12.0,
                'description' => 'This 12kWh Lithium-Ion (NMC) battery is built for high-power applications. It offers excellent power density and round-trip efficiency, perfect for off-grid homes requiring large loads.',
            ],
            [
                'name' => 'PowerFlow Stack 7.5',
                'manufacturer_id' => 14,
                'price' => 1100.0,
                'capacity' => 7.5,
                'description' => 'The PowerFlow Stack 7.5 is a 7.5kWh modular LFP battery. You can stack up to four units for a total of 30kWh, making it a flexible solution for growing energy needs.',
            ],
            [
                'name' => 'GridCore WallMount 8',
                'manufacturer_id' => 8,
                'price' => 1250.0,
                'capacity' => 8.0,
                'description' => 'This 8kWh LiFePO4 battery features a slim, wall-mountable design. It integrates seamlessly into your home and provides reliable backup power during grid outages.',
            ],
            [
                'name' => 'ElementVolt LFP 14',
                'manufacturer_id' => 6,
                'price' => 1900.0,
                'capacity' => 14.0,
                'description' => 'The ElementVolt LFP 14 is a high-capacity 14kWh battery. It uses cobalt-free LiFePO4 chemistry, offering superior safety, thermal stability, and an exceptionally long lifespan.',
            ],
            [
                'name' => 'ZenithStorage Z-Bank 4',
                'manufacturer_id' => 27,
                'price' => 600.0,
                'capacity' => 4.0,
                'description' => 'A 4kWh LFP battery module that is rack-mountable for easy installation. It\'s a scalable solution, perfect for building custom-sized battery banks for off-grid or commercial use.',
            ],
            [
                'name' => 'TerraCharge HomeBase 10',
                'manufacturer_id' => 23,
                'price' => 1550.0,
                'capacity' => 10.0,
                'description' => 'The 10kWh TerraCharge HomeBase provides dependable energy storage. Its integrated smart BMS communicates directly with leading inverters for optimized charging and discharging cycles.',
            ],
            [
                'name' => 'EcoCharge HomeVault 13.5',
                'manufacturer_id' => 5,
                'price' => 1850.0,
                'capacity' => 13.5,
                'description' => 'The 13.5kWh HomeVault is a high-capacity LiFePO4 battery. It\'s designed for full home backup, ensuring your lights and essential appliances stay on during any outage.',
            ],
            [
                'name' => 'Quantum EnergyBank 7',
                'manufacturer_id' => 15,
                'price' => 1050.0,
                'capacity' => 7.0,
                'description' => 'This 7kWh LiFePO4 battery offers a great balance of capacity and price. It\'s perfect for residential users looking to maximize their solar self-consumption.',
            ],
            [
                'name' => 'AuraPower Reserve 10',
                'manufacturer_id' => 4,
                'price' => 1450.0,
                'capacity' => 10.0,
                'description' => 'The AuraPower Reserve 10 is a 10kWh modular battery. Its sleek design and scalable architecture make it a popular choice for modern, energy-smart homes.',
            ],
            [
                'name' => 'VoltStorage Core 2.5',
                'manufacturer_id' => 25,
                'price' => 299.99,
                'capacity' => 2.5,
                'description' => 'The VoltStorage Core 2.5 is a compact 2.5kWh LFP battery. It\'s an ideal entry-point for solar storage, helping you optimize self-consumption and reduce your electricity bills.',
            ],
            [
                'name' => 'AmpereDrive Titan 12',
                'manufacturer_id' => 2,
                'price' => 1750.0,
                'capacity' => 12.0,
                'description' => 'This 12kWh Lithium-Ion (NMC) battery is built for high-power applications. It offers excellent power density and round-trip efficiency, perfect for off-grid homes requiring large loads.',
            ],
            [
                'name' => 'PowerFlow Stack 7.5',
                'manufacturer_id' => 14,
                'price' => 1100.0,
                'capacity' => 7.5,
                'description' => 'The PowerFlow Stack 7.5 is a 7.5kWh modular LFP battery. You can stack up to four units for a total of 30kWh, making it a flexible solution for growing energy needs.',
            ],
            [
                'name' => 'GridCore WallMount 8',
                'manufacturer_id' => 8,
                'price' => 1250.0,
                'capacity' => 8.0,
                'description' => 'This 8kWh LiFePO4 battery features a slim, wall-mountable design. It integrates seamlessly into your home and provides reliable backup power during grid outages.',
            ],
            [
                'name' => 'ElementVolt LFP 14',
                'manufacturer_id' => 6,
                'price' => 1900.0,
                'capacity' => 14.0,
                'description' => 'The ElementVolt LFP 14 is a high-capacity 14kWh battery. It uses cobalt-free LiFePO4 chemistry, offering superior safety, thermal stability, and an exceptionally long lifespan.',
            ],
            [
                'name' => 'ZenithStorage Z-Bank 4',
                'manufacturer_id' => 27,
                'price' => 600.0,
                'capacity' => 4.0,
                'description' => 'A 4kWh LFP battery module that is rack-mountable for easy installation. It\'s a scalable solution, perfect for building custom-sized battery banks for off-grid or commercial use.',
            ],
            [
                'name' => 'TerraCharge HomeBase 10',
                'manufacturer_id' => 23,
                'price' => 1550.0,
                'capacity' => 10.0,
                'description' => 'The 10kWh TerraCharge HomeBase provides dependable energy storage. Its integrated smart BMS communicates directly with leading inverters for optimized charging and discharging cycles.',
            ],
            [
                'name' => 'EcoCharge HomeVault 13.5',
                'manufacturer_id' => 5,
                'price' => 1850.0,
                'capacity' => 13.5,
                'description' => 'The 13.5kWh HomeVault is a high-capacity LiFePO4 battery. It\'s designed for full home backup, ensuring your lights and essential appliances stay on during any outage.',
            ],
            [
                'name' => 'Quantum EnergyBank 7',
                'manufacturer_id' => 15,
                'price' => 1050.0,
                'capacity' => 7.0,
                'description' => 'This 7kWh LiFePO4 battery offers a great balance of capacity and price. It\'s perfect for residential users looking to maximize their solar self-consumption.',
            ],
            [
                'name' => 'AuraPower Reserve 10',
                'manufacturer_id' => 4,
                'price' => 1450.0,
                'capacity' => 10.0,
                'description' => 'The AuraPower Reserve 10 is a 10kWh modular battery. Its sleek design and scalable architecture make it a popular choice for modern, energy-smart homes.',
            ],
            [
                'name' => 'VoltStorage Core 5',
                'manufacturer_id' => 25,
                'price' => 760.0,
                'capacity' => 5.0,
                'description' => 'A 5kWh LFP battery that is simple to install and operate. The VoltStorage Core 5 is a robust, no-fuss solution for adding energy storage to any solar PV system.',
            ],
            [
                'name' => 'AmpereDrive Titan 9',
                'manufacturer_id' => 2,
                'price' => 1300.0,
                'capacity' => 9.0,
                'description' => 'This 9kWh NMC battery delivers high power output in a compact form factor. It\'s ideal for homes with high peak energy demands, like those with EV chargers.',
            ],
            [
                'name' => 'PowerFlow Stack 3.5',
                'manufacturer_id' => 14,
                'price' => 499.0,
                'capacity' => 3.5,
                'description' => 'The 3.5kWh PowerFlow Stack is the base module for their scalable system. Start with one and add more later as your energy storage requirements increase.',
            ],
            [
                'name' => 'GridCore WallMount 11',
                'manufacturer_id' => 8,
                'price' => 1600.0,
                'capacity' => 11.0,
                'description' => 'This 11kWh wall-mounted LFP battery features an integrated DC disconnect. This simplifies installation and provides a clean, all-in-one look in your garage or utility room.',
            ],
            [
                'name' => 'ElementVolt LFP 6.5',
                'manufacturer_id' => 6,
                'price' => 950.0,
                'capacity' => 6.5,
                'description' => 'A 6.5kWh LiFePO4 battery with a very high cycle life. It\'s engineered for durability and is an excellent choice for off-grid applications where reliability is paramount.',
            ],
            [
                'name' => 'ZenithStorage Z-Bank 2.4',
                'manufacturer_id' => 27,
                'price' => 350.0,
                'capacity' => 2.4,
                'description' => 'This 2.4kWh rack-mounted LFP module is a favorite for DIYers and system integrators. It offers robust performance and is easily paralleled for larger system builds.',
            ],
            [
                'name' => 'TerraCharge HomeBase 12',
                'manufacturer_id' => 23,
                'price' => 1700.0,
                'capacity' => 12.0,
                'description' => 'The 12kWh TerraCharge HomeBase is a smart battery. It can be programmed for time-of-use arbitrage, charging from the grid when rates are low and powering your home when they are high.',
            ],
            [
                'name' => 'EcoCharge HomeVault 7.5',
                'manufacturer_id' => 5,
                'price' => 1150.0,
                'capacity' => 7.5,
                'description' => 'A 7.5kWh LFP battery from the reliable HomeVault series. It\'s a mid-sized option perfect for many homes, providing both blackout protection and daily energy cycling.',
            ],
            [
                'name' => 'Quantum EnergyBank 10',
                'manufacturer_id' => 15,
                'price' => 1480.0,
                'capacity' => 10.0,
                'description' => 'The 10kWh EnergyBank is a complete home storage solution. It features a wide operating temperature range, making it suitable for installation in garages or sheds.',
            ],
            [
                'name' => 'AuraPower Reserve 5',
                'manufacturer_id' => 4,
                'price' => 770.0,
                'capacity' => 5.0,
                'description' => 'This 5kWh stackable module is the building block of the AuraPower system. Its simple plug-and-play connectivity makes installation fast and straightforward for certified installers.',
            ],
            [
                'name' => 'VoltStorage Core 8',
                'manufacturer_id' => 25,
                'price' => 1200.0,
                'capacity' => 8.0,
                'description' => 'The 8kWh VoltStorage Core offers reliable LiFePO4 storage. It is designed for longevity, providing over 10 years of service under normal daily cycling conditions.',
            ],
            [
                'name' => 'AmpereDrive Titan 15',
                'manufacturer_id' => 2,
                'price' => 1999.0,
                'capacity' => 15.0,
                'description' => 'The 15kWh Titan is a high-capacity NMC battery for large homes. Its high discharge rate can power multiple heavy-duty appliances simultaneously during an outage.',
            ],
            [
                'name' => 'PowerFlow Stack 10.5',
                'manufacturer_id' => 14,
                'price' => 1550.0,
                'capacity' => 10.5,
                'description' => 'This 10.5kWh battery system is comprised of three 3.5kWh modules. This modularity simplifies transportation and installation, allowing for a one-person setup.',
            ],
            [
                'name' => 'GridCore WallMount 4',
                'manufacturer_id' => 8,
                'price' => 650.0,
                'capacity' => 4.0,
                'description' => 'A compact 4kWh wall-mounted LFP battery. It\'s the perfect size for apartments or small homes looking to offset evening energy consumption with stored solar power.',
            ],
            [
                'name' => 'ElementVolt LFP 9',
                'manufacturer_id' => 6,
                'price' => 1320.0,
                'capacity' => 9.0,
                'description' => 'The 9kWh ElementVolt battery is built with prismatic LiFePO4 cells for maximum safety. It includes a smart BMS with Wi-Fi monitoring to track your energy usage.',
            ],
            [
                'name' => 'ZenithStorage Z-Bank 3.5',
                'manufacturer_id' => 27,
                'price' => 480.0,
                'capacity' => 3.5,
                'description' => 'A 3.5kWh 48V rack battery module. These are easy to parallel, allowing for highly customized battery bank sizes to perfectly match your inverter and load profile.',
            ],
            [
                'name' => 'TerraCharge HomeBase 8',
                'manufacturer_id' => 23,
                'price' => 1220.0,
                'capacity' => 8.0,
                'description' => 'The 8kWh TerraCharge HomeBase is a smart LFP battery. It integrates with smart home platforms, allowing you to optimize your energy storage around your daily routines.',
            ],
            [
                'name' => 'EcoCharge HomeVault 12',
                'manufacturer_id' => 5,
                'price' => 1720.0,
                'capacity' => 12.0,
                'description' => 'This 12kWh LFP battery provides reliable backup for most of your home. It features a high round-trip efficiency, ensuring more of your stored solar energy is available for use.',
            ],
            [
                'name' => 'Quantum EnergyBank 3',
                'manufacturer_id' => 15,
                'price' => 450.0,
                'capacity' => 3.0,
                'description' => 'An entry-level 3kWh LFP battery for load shifting. It\'s an affordable way to start with energy storage and reduce your reliance on the grid during peak hours.',
            ],
            [
                'name' => 'AuraPower Reserve 12.5',
                'manufacturer_id' => 4,
                'price' => 1799.0,
                'capacity' => 12.5,
                'description' => 'A 12.5kWh (five 2.5kWh modules) stackable LFP system. The AuraPower Reserve\'s modular design makes it easy to install without heavy lifting equipment.',
            ],
            [
                'name' => 'VoltStorage Core 6.5',
                'manufacturer_id' => 25,
                'price' => 975.0,
                'capacity' => 6.5,
                'description' => 'The 6.5kWh VoltStorage Core is a dependable LFP battery. It\'s designed for simple integration with grid-tied or hybrid inverters, providing a reliable storage solution.',
            ],
            [
                'name' => 'AmpereDrive Titan 10',
                'manufacturer_id' => 2,
                'price' => 1500.0,
                'capacity' => 10.0,
                'description' => 'This 10kWh NMC battery is a high-performance unit. Its chemistry allows for fast charging and discharging, making it ideal for capturing maximum solar energy.',
            ],
            [
                'name' => 'PowerFlow Stack 7',
                'manufacturer_id' => 14,
                'price' => 1080.0,
                'capacity' => 7.0,
                'description' => 'A 7kWh (two 3.5kWh modules) LFP battery system. This mid-sized solution is perfect for a typical family home, providing overnight power and backup.',
            ],
            [
                'name' => 'GridCore WallMount 9',
                'manufacturer_id' => 8,
                'price' => 1350.0,
                'capacity' => 9.0,
                'description' => 'The 9kWh GridCore LFP battery features a sleek, integrated design. Its wall-mounting bracket is included, making for a clean and professional-looking installation.',
            ],
            [
                'name' => 'ElementVolt LFP 11',
                'manufacturer_id' => 6,
                'price' => 1620.0,
                'capacity' => 11.0,
                'description' => 'A robust 11kWh LiFePO4 battery built for longevity. It\'s an ideal storage solution for off-grid cabins or homes that experience frequent, extended power outages.',
            ],
            [
                'name' => 'ZenithStorage Z-Bank 4.8',
                'manufacturer_id' => 27,
                'price' => 720.0,
                'capacity' => 4.8,
                'description' => 'This 4.8kWh 48V rack battery is a top-seller. Its high-quality LFP cells and smart BMS ensure reliable performance and compatibility with a wide range of inverters.',
            ],
            [
                'name' => 'TerraCharge HomeBase 14',
                'manufacturer_id' => 23,
                'price' => 1950.0,
                'capacity' => 14.0,
                'description' => 'The 14kWh TerraCharge HomeBase is a premium LFP storage solution. It offers deep cycling capabilities and a sophisticated thermal management system for a long, reliable service life.',
            ],
        ]);
    }
}
